---
abstract: 'Perl 5 interface to Java JDBC (via Inline::Java)'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JDBC
provides:
  JDBC:
    file: lib/JDBC.pm
    version: 0.02
requires:
  Inline::Java: 0.50
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
